export const selectStone = [
  {
    id: 1,
    value: "diamond",
    label: "Diamond",
    image: "/images/18KT-LOGO-100x-2x.png",
    imageWidth: 96,
    imageHeight: 62,
    imageUnit: "px",
  },
  {
    id: 2,
    value: "coloredGemstone",
    label: "Colored Gemstone",
    image: "/images/18KT-LOGO-100x-2x.png",
    imageWidth: 96,
    imageHeight: 62,
    imageUnit: "px",
    selected: true,
  },
  {
    id: 3,
    value: "moissanite",
    label: "Moissanite",
    image: "/images/18KT-LOGO-100x-2x.png",
    imageWidth: 96,
    imageHeight: 62,
    imageUnit: "px",
  },
  {
    id: 4,
    value: "noStone",
    label: "No Stone",
    image: "/images/18KT-LOGO-100x-2x.png",
    imageWidth: 96,
    imageHeight: 62,
    imageUnit: "px",
  },
];
